export const enum INJECTION_KEYS {
    DbContext = 'DB_CONTEXT',
    CategoryService = 'CategoryService',
    UserService = 'UserService'
}

export const enum ConfigurationParameters {
    DATABASE_TYPE = 'DATABASE_TYPE',
    DATABASE_HOST = 'DATABASE_HOST',
    DATABASE_PORT = 'DATABASE_PORT',
    DATABASE_USER = 'DATABASE_USER',
    DATABASE_PASSWORD = 'DATABASE_PASSWORD',
    DATABASE_NAME = 'DATABASE_NAME',
    DATABASE_SYNCHRONIZE = 'DATABASE_SYNCHRONIZE',
    DATABASE_LOGGING = 'DATABASE_LOGGING',
    LOG_DESTINATION_FILES = 'LOG_DESTINATION_FILES',
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRES = 'JWT_EXPIRES',
    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT'
}
